# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            nerdyjkg
tagline:          nascent blog of @nerdyjkg
url:              http://jgallagher.github.io
paginate:         1
baseurl:          /
author:
  name:           John Gallagher
  url:            https://twitter.com/nerdyjkg
  email:          johnkgallagher@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jgallagher/jgallagher.github.io
